### ISSUE TITLE
The result of (sha1 "你好") is error.

### ISSUE THREAD

**Issue by QinAIns** [xsc/pandect#10]
"http://pajhome.org.uk/crypt/md5/index.html" in this site,the result of 
hex_sha1("你好") is "440ee0853ad1e99f962b63e459ef992d7c211722".
But the result of 
(pandect.algo.sha1/sha1 "你好") is "4bd9abaa33ea0834383e15fef9ae377f762fc03b".
 As far as I know,the correct of the result is "440ee0853ad1e99f962b63e459ef992d7c211722". Is there something wrong in pandect.algo.sha1/sha1 function?

**Comment by QinAIns** [comment]
hex_md5("你好") is "7eca689f0d3389d9dea66ae112e5cfd7". But 
(pandect.algo.md5/md5 "你好") is "b94ae3c6d892b29cf48d9bea819b27b9"

**Comment by xsc** [comment]
Your default charset does not seem to be UTF-8. For me, it's working:

```clojure
(require '[pandect.algo [sha1 :refer [sha1]] [md5 :refer [md5]]])
(let [data "你好"]
  [(sha1 data) (md5 data)])
;; => ["440ee0853ad1e99f962b63e459ef992d7c211722"
;;     "7eca689f0d3389d9dea66ae112e5cfd7"]
```

The following should give you the right result:

```clojure
(sha1 (.getBytes "你好" "UTF-8"))
```

But yes, pandect should by default convert to UTF-8 bytes.

**Comment by xsc** [comment]
Changes were released in

```clojure
[pandect "0.5.0"]
```

**Comment by QinAIns** [comment]
:+1:
