### ISSUE TITLE
Add Support for BLAKE2

### ISSUE THREAD

**Issue by espeed** [xsc/pandect#4]
BLAKE2 overview: https://blake2.net/

**Comment by zooko** [comment]
Bouncy Castle 1.54, released 2015-12-29, comes with BLAKE2! ☺ https://www.bouncycastle.org/releasenotes.html

**Comment by xsc** [comment]
The BLAKE2b variants provided by BouncyCastle have been released in

```clojure
[pandect "0.6.0"]
```

I also adjusted the way BouncyCastle algorithms are used, removing most of the BC-specific code, so we should have it easier to add new algorithms in future.
