### ISSUE TITLE
Security Exception

### ISSUE THREAD

**Issue by mgadzhi** [xsc/pandect#6]
When trying to require pandect.core in repl, I get this exception:
(require '[pandect.core :refer :all])

CompilerException java.lang.SecurityException: class "org.bouncycastle.crypto.digests.SHA3Digest"'s signer information does not match signer information of other classes in the same package, compiling:(pandect/algo/sha3_512.clj:87:8)
The version I tried is [pandect "0.4.0"] as is recommended in repos README.

P.S. I couldn't reproduce this behavior in cloned repo though.

**Comment by patelvikash** [comment]
01220002 Failed to execute script 'workspace://SpacesStore/2992ebb4-1921-4373-b5d7-8393d3e34e1a': class "org.bouncycastle.crypto.digests.SHA3Digest"'s signer information does not match signer information of other classes in the same package

**Comment by xsc** [comment]
@patelvikash Can you paste the output of the following command?

```shell
lein deps :tree | grep bouncy
```

Maybe you, too, have multiple BouncyCastle dependencies conflicting with each other. Also, what version of pandect are we talking about?
